# Imports
group_imports = "StdExternalCrate"
imports_granularity = "Module"

# Turn on more formatting that is disabled by default.
format_code_in_doc_comments = true
format_strings = true
hex_literal_case = "Upper"
normalize_doc_attributes = true
wrap_comments = true
use_try_shorthand = true

# Make things more compact.
fn_single_line = true
match_arm_blocks = false
use_small_heuristics = "Max"
inline_attribute_width = 50

# Line up.
enum_discrim_align_threshold = 50
struct_field_align_threshold = 50
