[keyboard]
bindings = [
  { key = "Return", mods = "Command", action = "ToggleSimpleFullscreen" }
]

[font.normal]
# family = "Menlo"
# family = "Monaco"
family = "Iosevka Light"

[font]
size = 16

[window]
decorations = "none"
startup_mode = "SimpleFullscreen"

[general]
import = ["~/dotfiles/vendor/alacritty-theme/themes/kanagawa_dragon.toml"]
