[keyboard]
bindings = [
  { key = "Return", mods = "Command", action = "ToggleSimpleFullscreen" },
  # Unbind macOS default Cmd+K because I ~never want ClearHistory
  { key = "K", mods = "Command", mode = "~Vi|~Search", action = "None" },
]

[font.normal]
# family = "Menlo"
# family = "Monaco"
family = "Iosevka Light"

[font]
size = 16

[window]
decorations = "none"
startup_mode = "SimpleFullscreen"

[general]
import = ["~/dotfiles/.config/alacritty/generated-theme.toml"]
