import = ["~/dotfiles/vendor/alacritty-theme/themes/kanagawa_dragon.toml"]

[keyboard]
bindings = [
  { key = "Return", mods = "Command", action = "ToggleSimpleFullscreen" }
]

[font.normal]
family = "Menlo"
# family = "Iosevka"
# family = "Monaco"

[font]
size = 12

[window]
decorations = "none"
startup_mode = "SimpleFullscreen"
