import = ["~/dotfiles/vendor/alacritty-theme/themes/github_dark_dimmed.toml"]

[keyboard]
bindings = [
  { key = "Return", mods = "Command", action = "ToggleSimpleFullscreen" }
]

[font.normal]
family = "Iosevka Light"

[font]
size = 15

[window]
decorations = "none"
startup_mode = "SimpleFullscreen"
