[keyboard]
bindings = [
  { key = "Return", mods = "Command", action = "ToggleSimpleFullscreen" }
]

[font.normal]
family = "Menlo"
# family = "Iosevka Extralight"
# family = "Monaco"

[font]
size = 11

[window]
decorations = "none"
startup_mode = "SimpleFullscreen"

[general]
import = ["~/dotfiles/vendor/alacritty-theme/themes/kanagawa_dragon.toml"]
