theme = "kanagawa-dragon"

[editor]
cursorline = true
color-modes = true
idle-timeout = 0
rulers = [81, 93] # put ruler one past the final permissible character

[editor.soft-wrap]
enable = true

[editor.file-picker]
follow-symlinks = false

[editor.lsp]
display-messages = true

[keys.insert]
j = { k = "normal_mode" }

[keys.normal]
"b" = "select_prev_sibling"
"e" = "select_next_sibling"
"tab" = "expand_selection"
"S-tab" = "shrink_selection"
w = ":w"
q = ":q"
